# Generated by Django 3.1.2 on 2021-07-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Юзер id')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('ref_link', models.CharField(max_length=255, unique=True, verbose_name='реферальная ссылка')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры бота',
            },
        ),
    ]
