# Generated by Django 3.1.2 on 2021-07-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210708_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
    ]
