# Generated by Django 3.1.2 on 2021-07-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210708_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': False, 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
